all:
  children:
    dbservers:
      hosts:
        db1.local:
          ansible_connection: local
          db_engine: postgresql
          db_port: 5432
        db2.local:
          ansible_connection: local
          db_engine: postgresql
          db_port: 5432
    local:
      hosts:
        localhost:
          ansible_connection: local
    webservers:
      hosts:
        web1.local:
          ansible_connection: local
          http_port: 8080
        web2.local:
          ansible_connection: local
          http_port: 8080